version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./configuration.yml:/var/jenkins_home/casc_configs/configuration.yml
      - jenkins_data:/var/jenkins_home
      - ./job_dsl.groovy:/var/jenkins_home/job_dsl.groovy
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs/configuration.yml
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
volumes:
  jenkins_data:
